apiVersion: v1
kind: Secret
metadata:
  name: svc-grocery-secrets
  namespace: grocery-dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/grocery_db"
  JWT_SECRET: "your-production-jwt-secret-at-least-32-chars"
